import { Extension, textInputRule } from "@tiptap/core";

/**
 * A smilie only counts as a word of its own: without the lookbehind, "ID: "
 * became "I😨 " and "Typ:b " a tongue. `^` is the start of the textblock.
 */
function smilie(find: RegExp, replace: string) {
  return textInputRule({
    find: new RegExp(`(?<=^|\\s)${find.source}`),
    replace,
  });
}

/**
 * Replaces ASCII smilies with emoji as you type — e.g. `:-)` → 🙂, `<3` → ❤️,
 * `>:P` → 😜, `/shrug` → ¯\_(ツ)_/¯. Each rule fires on the trailing space, so
 * you only get an emoji once the smilie is complete. Input rules produce plain
 * text insertions, which sync through the collaborative document like any other
 * edit. Adapted from Tiptap's "clever editor" example.
 *
 * `B)`, `8)` and `X)` are deliberately missing: that is how people enumerate
 * ("A) … B) …"), and a list label turning into 😎 is never what was meant.
 */
export const SmilieReplacer = Extension.create({
  name: "smilieReplacer",

  addInputRules() {
    return [
      smilie(/-___- $/, "😑 "),
      smilie(/:'-\) $/, "😂 "),
      smilie(/':-\) $/, "😅 "),
      smilie(/':-D $/, "😅 "),
      smilie(/>:-\) $/, "😆 "),
      smilie(/-__- $/, "😑 "),
      smilie(/':-\( $/, "😓 "),
      smilie(/:'-\( $/, "😢 "),
      smilie(/>:-\( $/, "😠 "),
      smilie(/O:-\) $/, "😇 "),
      smilie(/0:-3 $/, "😇 "),
      smilie(/0:-\) $/, "😇 "),
      smilie(/0;\^\) $/, "😇 "),
      smilie(/O;-\) $/, "😇 "),
      smilie(/0;-\) $/, "😇 "),
      smilie(/O:-3 $/, "😇 "),
      smilie(/:'\) $/, "😂 "),
      smilie(/:-D $/, "😃 "),
      smilie(/':\) $/, "😅 "),
      smilie(/'=\) $/, "😅 "),
      smilie(/':D $/, "😅 "),
      smilie(/'=D $/, "😅 "),
      smilie(/>:\) $/, "😆 "),
      smilie(/>;\) $/, "😆 "),
      smilie(/>=\) $/, "😆 "),
      smilie(/;-\) $/, "😉 "),
      smilie(/\*-\) $/, "😉 "),
      smilie(/;-\] $/, "😉 "),
      smilie(/;\^\) $/, "😉 "),
      smilie(/B-\) $/, "😎 "),
      smilie(/8-\) $/, "😎 "),
      smilie(/B-D $/, "😎 "),
      smilie(/8-D $/, "😎 "),
      smilie(/:-\* $/, "😘 "),
      smilie(/:\^\* $/, "😘 "),
      smilie(/:-\) $/, "🙂 "),
      smilie(/-_- $/, "😑 "),
      smilie(/:-X $/, "😶 "),
      smilie(/:-# $/, "😶 "),
      smilie(/:-x $/, "😶 "),
      smilie(/>.< $/, "😣 "),
      smilie(/:-O $/, "😮 "),
      smilie(/:-o $/, "😮 "),
      smilie(/O_O $/, "😮 "),
      smilie(/>:O $/, "😮 "),
      smilie(/:-P $/, "😛 "),
      smilie(/:-p $/, "😛 "),
      smilie(/:-Þ $/, "😛 "),
      smilie(/:-þ $/, "😛 "),
      smilie(/:-b $/, "😛 "),
      smilie(/>:P $/, "😜 "),
      smilie(/X-P $/, "😜 "),
      smilie(/x-p $/, "😜 "),
      smilie(/':\( $/, "😓 "),
      smilie(/'=\( $/, "😓 "),
      smilie(/>:\\ $/, "😕 "),
      smilie(/>:\/ $/, "😕 "),
      smilie(/:-\/ $/, "😕 "),
      smilie(/:-. $/, "😕 "),
      smilie(/>:\[ $/, "😞 "),
      smilie(/:-\( $/, "😞 "),
      smilie(/:-\[ $/, "😞 "),
      smilie(/:'\( $/, "😢 "),
      smilie(/;-\( $/, "😢 "),
      smilie(/#-\) $/, "😵 "),
      smilie(/%-\) $/, "😵 "),
      smilie(/X-\) $/, "😵 "),
      smilie(/>:\( $/, "😠 "),
      smilie(/0:3 $/, "😇 "),
      smilie(/0:\) $/, "😇 "),
      smilie(/O:\) $/, "😇 "),
      smilie(/O=\) $/, "😇 "),
      smilie(/O:3 $/, "😇 "),
      smilie(/<\/3 $/, "💔 "),
      smilie(/:D $/, "😃 "),
      smilie(/=D $/, "😃 "),
      smilie(/;\) $/, "😉 "),
      smilie(/\*\) $/, "😉 "),
      smilie(/;\] $/, "😉 "),
      smilie(/;D $/, "😉 "),
      smilie(/:\* $/, "😘 "),
      smilie(/=\* $/, "😘 "),
      smilie(/:\) $/, "🙂 "),
      smilie(/=\] $/, "🙂 "),
      smilie(/=\) $/, "🙂 "),
      smilie(/:\] $/, "🙂 "),
      smilie(/:X $/, "😶 "),
      smilie(/:# $/, "😶 "),
      smilie(/=X $/, "😶 "),
      smilie(/=x $/, "😶 "),
      smilie(/:x $/, "😶 "),
      smilie(/=# $/, "😶 "),
      smilie(/:O $/, "😮 "),
      smilie(/:o $/, "😮 "),
      smilie(/:P $/, "😛 "),
      smilie(/=P $/, "😛 "),
      smilie(/:p $/, "😛 "),
      smilie(/=p $/, "😛 "),
      smilie(/:Þ $/, "😛 "),
      smilie(/:þ $/, "😛 "),
      smilie(/:b $/, "😛 "),
      smilie(/d: $/, "😛 "),
      smilie(/:\/ $/, "😕 "),
      smilie(/:\\ $/, "😕 "),
      smilie(/=\/ $/, "😕 "),
      smilie(/=\\ $/, "😕 "),
      smilie(/:L $/, "😕 "),
      smilie(/=L $/, "😕 "),
      smilie(/:\( $/, "😞 "),
      smilie(/:\[ $/, "😞 "),
      smilie(/=\( $/, "😞 "),
      smilie(/;\( $/, "😢 "),
      smilie(/D: $/, "😨 "),
      smilie(/:\$ $/, "😳 "),
      smilie(/=\$ $/, "😳 "),
      smilie(/#\) $/, "😵 "),
      smilie(/%\) $/, "😵 "),
      smilie(/:@ $/, "😠 "),
      smilie(/<3 $/, "❤️ "),
      smilie(/\/shrug $/, "¯\\_(ツ)_/¯"),
    ];
  },
});
