/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AuthTagsRouteImport } from './routes/_auth/tags'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthInboxRouteImport } from './routes/_auth/inbox'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSpacesIndexRouteImport } from './routes/_auth/spaces/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthUsersIdRouteImport } from './routes/_auth/users/$id'
import { Route as AuthSpacesSlugRouteImport } from './routes/_auth/spaces/$slug'
import { Route as AuthSettingsWebhooksRouteImport } from './routes/_auth/settings/webhooks'
import { Route as AuthSettingsTeamsRouteImport } from './routes/_auth/settings/teams'
import { Route as AuthSettingsSsoRouteImport } from './routes/_auth/settings/sso'
import { Route as AuthSettingsSecurityPolicyRouteImport } from './routes/_auth/settings/security-policy'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsOrganizationRouteImport } from './routes/_auth/settings/organization'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings/notifications'
import { Route as AuthSettingsNotificationDefaultsRouteImport } from './routes/_auth/settings/notification-defaults'
import { Route as AuthSettingsMembersRouteImport } from './routes/_auth/settings/members'
import { Route as AuthSettingsGroupsRouteImport } from './routes/_auth/settings/groups'
import { Route as AuthSettingsDataLifecycleRouteImport } from './routes/_auth/settings/data-lifecycle'
import { Route as AuthSettingsAppearanceRouteImport } from './routes/_auth/settings/appearance'
import { Route as AuthPagesIdRouteImport } from './routes/_auth/pages/$id'
import { Route as AuthAdminAuditRouteImport } from './routes/_auth/admin/audit'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users/index'
import { Route as AuthAdminOrganizationsIndexRouteImport } from './routes/_auth/admin/organizations/index'
import { Route as AuthAdminUsersUserIdRouteImport } from './routes/_auth/admin/users/$userId'
import { Route as AuthAdminOrganizationsOrganizationIdRouteImport } from './routes/_auth/admin/organizations/$organizationId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTagsRoute = AuthTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInboxRoute = AuthInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpacesIndexRoute = AuthSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthUsersIdRoute = AuthUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpacesSlugRoute = AuthSpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsWebhooksRoute = AuthSettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsTeamsRoute = AuthSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsSsoRoute = AuthSettingsSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsSecurityPolicyRoute =
  AuthSettingsSecurityPolicyRouteImport.update({
    id: '/security-policy',
    path: '/security-policy',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsOrganizationRoute =
  AuthSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsNotificationDefaultsRoute =
  AuthSettingsNotificationDefaultsRouteImport.update({
    id: '/notification-defaults',
    path: '/notification-defaults',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsMembersRoute = AuthSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsGroupsRoute = AuthSettingsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsDataLifecycleRoute =
  AuthSettingsDataLifecycleRouteImport.update({
    id: '/data-lifecycle',
    path: '/data-lifecycle',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsAppearanceRoute = AuthSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthPagesIdRoute = AuthPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminAuditRoute = AuthAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminOrganizationsIndexRoute =
  AuthAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminUsersUserIdRoute = AuthAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminOrganizationsOrganizationIdRoute =
  AuthAdminOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/inbox': typeof AuthInboxRoute
  '/search': typeof AuthSearchRoute
  '/tags': typeof AuthTagsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/data-lifecycle': typeof AuthSettingsDataLifecycleRoute
  '/settings/groups': typeof AuthSettingsGroupsRoute
  '/settings/members': typeof AuthSettingsMembersRoute
  '/settings/notification-defaults': typeof AuthSettingsNotificationDefaultsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/settings/sso': typeof AuthSettingsSsoRoute
  '/settings/teams': typeof AuthSettingsTeamsRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksRoute
  '/spaces/$slug': typeof AuthSpacesSlugRoute
  '/users/$id': typeof AuthUsersIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/spaces/': typeof AuthSpacesIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/admin/organizations/$organizationId': typeof AuthAdminOrganizationsOrganizationIdRoute
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/organizations/': typeof AuthAdminOrganizationsIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AuthInboxRoute
  '/search': typeof AuthSearchRoute
  '/tags': typeof AuthTagsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/': typeof AuthIndexRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/data-lifecycle': typeof AuthSettingsDataLifecycleRoute
  '/settings/groups': typeof AuthSettingsGroupsRoute
  '/settings/members': typeof AuthSettingsMembersRoute
  '/settings/notification-defaults': typeof AuthSettingsNotificationDefaultsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/settings/sso': typeof AuthSettingsSsoRoute
  '/settings/teams': typeof AuthSettingsTeamsRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksRoute
  '/spaces/$slug': typeof AuthSpacesSlugRoute
  '/users/$id': typeof AuthUsersIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/spaces': typeof AuthSpacesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/admin/organizations/$organizationId': typeof AuthAdminOrganizationsOrganizationIdRoute
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/organizations': typeof AuthAdminOrganizationsIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/inbox': typeof AuthInboxRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/tags': typeof AuthTagsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/audit': typeof AuthAdminAuditRoute
  '/_auth/pages/$id': typeof AuthPagesIdRoute
  '/_auth/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/_auth/settings/data-lifecycle': typeof AuthSettingsDataLifecycleRoute
  '/_auth/settings/groups': typeof AuthSettingsGroupsRoute
  '/_auth/settings/members': typeof AuthSettingsMembersRoute
  '/_auth/settings/notification-defaults': typeof AuthSettingsNotificationDefaultsRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/organization': typeof AuthSettingsOrganizationRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/_auth/settings/sso': typeof AuthSettingsSsoRoute
  '/_auth/settings/teams': typeof AuthSettingsTeamsRoute
  '/_auth/settings/webhooks': typeof AuthSettingsWebhooksRoute
  '/_auth/spaces/$slug': typeof AuthSpacesSlugRoute
  '/_auth/users/$id': typeof AuthUsersIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/spaces/': typeof AuthSpacesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/admin/organizations/$organizationId': typeof AuthAdminOrganizationsOrganizationIdRoute
  '/_auth/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/_auth/admin/organizations/': typeof AuthAdminOrganizationsIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/inbox'
    | '/search'
    | '/tags'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/admin/audit'
    | '/pages/$id'
    | '/settings/appearance'
    | '/settings/data-lifecycle'
    | '/settings/groups'
    | '/settings/members'
    | '/settings/notification-defaults'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/security-policy'
    | '/settings/sso'
    | '/settings/teams'
    | '/settings/webhooks'
    | '/spaces/$slug'
    | '/users/$id'
    | '/admin/'
    | '/settings/'
    | '/spaces/'
    | '/users/'
    | '/admin/organizations/$organizationId'
    | '/admin/users/$userId'
    | '/admin/organizations/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/search'
    | '/tags'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/'
    | '/admin/audit'
    | '/pages/$id'
    | '/settings/appearance'
    | '/settings/data-lifecycle'
    | '/settings/groups'
    | '/settings/members'
    | '/settings/notification-defaults'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/security-policy'
    | '/settings/sso'
    | '/settings/teams'
    | '/settings/webhooks'
    | '/spaces/$slug'
    | '/users/$id'
    | '/admin'
    | '/settings'
    | '/spaces'
    | '/users'
    | '/admin/organizations/$organizationId'
    | '/admin/users/$userId'
    | '/admin/organizations'
    | '/admin/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/admin'
    | '/_auth/settings'
    | '/_auth/inbox'
    | '/_auth/search'
    | '/_auth/tags'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/_auth/'
    | '/_auth/admin/audit'
    | '/_auth/pages/$id'
    | '/_auth/settings/appearance'
    | '/_auth/settings/data-lifecycle'
    | '/_auth/settings/groups'
    | '/_auth/settings/members'
    | '/_auth/settings/notification-defaults'
    | '/_auth/settings/notifications'
    | '/_auth/settings/organization'
    | '/_auth/settings/profile'
    | '/_auth/settings/security'
    | '/_auth/settings/security-policy'
    | '/_auth/settings/sso'
    | '/_auth/settings/teams'
    | '/_auth/settings/webhooks'
    | '/_auth/spaces/$slug'
    | '/_auth/users/$id'
    | '/_auth/admin/'
    | '/_auth/settings/'
    | '/_auth/spaces/'
    | '/_auth/users/'
    | '/_auth/admin/organizations/$organizationId'
    | '/_auth/admin/users/$userId'
    | '/_auth/admin/organizations/'
    | '/_auth/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tags': {
      id: '/_auth/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthTagsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/inbox': {
      id: '/_auth/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthInboxRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/spaces/': {
      id: '/_auth/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthSpacesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/users/$id': {
      id: '/_auth/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthUsersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/spaces/$slug': {
      id: '/_auth/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof AuthSpacesSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/webhooks': {
      id: '/_auth/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthSettingsWebhooksRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/teams': {
      id: '/_auth/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof AuthSettingsTeamsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/sso': {
      id: '/_auth/settings/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof AuthSettingsSsoRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/security-policy': {
      id: '/_auth/settings/security-policy'
      path: '/security-policy'
      fullPath: '/settings/security-policy'
      preLoaderRoute: typeof AuthSettingsSecurityPolicyRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/organization': {
      id: '/_auth/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/notification-defaults': {
      id: '/_auth/settings/notification-defaults'
      path: '/notification-defaults'
      fullPath: '/settings/notification-defaults'
      preLoaderRoute: typeof AuthSettingsNotificationDefaultsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/members': {
      id: '/_auth/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthSettingsMembersRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/groups': {
      id: '/_auth/settings/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AuthSettingsGroupsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/data-lifecycle': {
      id: '/_auth/settings/data-lifecycle'
      path: '/data-lifecycle'
      fullPath: '/settings/data-lifecycle'
      preLoaderRoute: typeof AuthSettingsDataLifecycleRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/appearance': {
      id: '/_auth/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthSettingsAppearanceRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/pages/$id': {
      id: '/_auth/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof AuthPagesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/audit': {
      id: '/_auth/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthAdminAuditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/organizations/': {
      id: '/_auth/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/$userId': {
      id: '/_auth/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthAdminUsersUserIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/organizations/$organizationId': {
      id: '/_auth/admin/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/admin/organizations/$organizationId'
      preLoaderRoute: typeof AuthAdminOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminAuditRoute: typeof AuthAdminAuditRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminOrganizationsOrganizationIdRoute: typeof AuthAdminOrganizationsOrganizationIdRoute
  AuthAdminUsersUserIdRoute: typeof AuthAdminUsersUserIdRoute
  AuthAdminOrganizationsIndexRoute: typeof AuthAdminOrganizationsIndexRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminAuditRoute: AuthAdminAuditRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminOrganizationsOrganizationIdRoute:
    AuthAdminOrganizationsOrganizationIdRoute,
  AuthAdminUsersUserIdRoute: AuthAdminUsersUserIdRoute,
  AuthAdminOrganizationsIndexRoute: AuthAdminOrganizationsIndexRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthSettingsRouteRouteChildren {
  AuthSettingsAppearanceRoute: typeof AuthSettingsAppearanceRoute
  AuthSettingsDataLifecycleRoute: typeof AuthSettingsDataLifecycleRoute
  AuthSettingsGroupsRoute: typeof AuthSettingsGroupsRoute
  AuthSettingsMembersRoute: typeof AuthSettingsMembersRoute
  AuthSettingsNotificationDefaultsRoute: typeof AuthSettingsNotificationDefaultsRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsOrganizationRoute: typeof AuthSettingsOrganizationRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsSecurityPolicyRoute: typeof AuthSettingsSecurityPolicyRoute
  AuthSettingsSsoRoute: typeof AuthSettingsSsoRoute
  AuthSettingsTeamsRoute: typeof AuthSettingsTeamsRoute
  AuthSettingsWebhooksRoute: typeof AuthSettingsWebhooksRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsAppearanceRoute: AuthSettingsAppearanceRoute,
  AuthSettingsDataLifecycleRoute: AuthSettingsDataLifecycleRoute,
  AuthSettingsGroupsRoute: AuthSettingsGroupsRoute,
  AuthSettingsMembersRoute: AuthSettingsMembersRoute,
  AuthSettingsNotificationDefaultsRoute: AuthSettingsNotificationDefaultsRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsOrganizationRoute: AuthSettingsOrganizationRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsSecurityPolicyRoute: AuthSettingsSecurityPolicyRoute,
  AuthSettingsSsoRoute: AuthSettingsSsoRoute,
  AuthSettingsTeamsRoute: AuthSettingsTeamsRoute,
  AuthSettingsWebhooksRoute: AuthSettingsWebhooksRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthInboxRoute: typeof AuthInboxRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthTagsRoute: typeof AuthTagsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthPagesIdRoute: typeof AuthPagesIdRoute
  AuthSpacesSlugRoute: typeof AuthSpacesSlugRoute
  AuthUsersIdRoute: typeof AuthUsersIdRoute
  AuthSpacesIndexRoute: typeof AuthSpacesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthInboxRoute: AuthInboxRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthTagsRoute: AuthTagsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthPagesIdRoute: AuthPagesIdRoute,
  AuthSpacesSlugRoute: AuthSpacesSlugRoute,
  AuthUsersIdRoute: AuthUsersIdRoute,
  AuthSpacesIndexRoute: AuthSpacesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
