/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthSpacesIndexRouteImport } from './routes/_auth/spaces/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSpacesSlugRouteImport } from './routes/_auth/spaces/$slug'
import { Route as AuthSettingsTeamsRouteImport } from './routes/_auth/settings/teams'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsOrganizationRouteImport } from './routes/_auth/settings/organization'
import { Route as AuthSettingsMembersRouteImport } from './routes/_auth/settings/members'
import { Route as AuthSettingsGroupsRouteImport } from './routes/_auth/settings/groups'
import { Route as AuthSettingsAppearanceRouteImport } from './routes/_auth/settings/appearance'
import { Route as AuthPagesIdRouteImport } from './routes/_auth/pages/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpacesIndexRoute = AuthSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSpacesSlugRoute = AuthSpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsTeamsRoute = AuthSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsOrganizationRoute =
  AuthSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsMembersRoute = AuthSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsGroupsRoute = AuthSettingsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsAppearanceRoute = AuthSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthPagesIdRoute = AuthPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/search': typeof AuthSearchRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/groups': typeof AuthSettingsGroupsRoute
  '/settings/members': typeof AuthSettingsMembersRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/teams': typeof AuthSettingsTeamsRoute
  '/spaces/$slug': typeof AuthSpacesSlugRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/spaces/': typeof AuthSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/search': typeof AuthSearchRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/': typeof AuthIndexRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/groups': typeof AuthSettingsGroupsRoute
  '/settings/members': typeof AuthSettingsMembersRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/teams': typeof AuthSettingsTeamsRoute
  '/spaces/$slug': typeof AuthSpacesSlugRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/spaces': typeof AuthSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/search': typeof AuthSearchRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/pages/$id': typeof AuthPagesIdRoute
  '/_auth/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/_auth/settings/groups': typeof AuthSettingsGroupsRoute
  '/_auth/settings/members': typeof AuthSettingsMembersRoute
  '/_auth/settings/organization': typeof AuthSettingsOrganizationRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/settings/teams': typeof AuthSettingsTeamsRoute
  '/_auth/spaces/$slug': typeof AuthSpacesSlugRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/spaces/': typeof AuthSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/search'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/pages/$id'
    | '/settings/appearance'
    | '/settings/groups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/teams'
    | '/spaces/$slug'
    | '/settings/'
    | '/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/search'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/'
    | '/pages/$id'
    | '/settings/appearance'
    | '/settings/groups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/teams'
    | '/spaces/$slug'
    | '/settings'
    | '/spaces'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/settings'
    | '/_auth/search'
    | '/accept-invitation/$id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/two-factor'
    | '/_auth/'
    | '/_auth/pages/$id'
    | '/_auth/settings/appearance'
    | '/_auth/settings/groups'
    | '/_auth/settings/members'
    | '/_auth/settings/organization'
    | '/_auth/settings/profile'
    | '/_auth/settings/security'
    | '/_auth/settings/teams'
    | '/_auth/spaces/$slug'
    | '/_auth/settings/'
    | '/_auth/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/spaces/': {
      id: '/_auth/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthSpacesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/spaces/$slug': {
      id: '/_auth/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof AuthSpacesSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/teams': {
      id: '/_auth/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof AuthSettingsTeamsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/organization': {
      id: '/_auth/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/members': {
      id: '/_auth/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthSettingsMembersRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/groups': {
      id: '/_auth/settings/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AuthSettingsGroupsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/appearance': {
      id: '/_auth/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthSettingsAppearanceRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/pages/$id': {
      id: '/_auth/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof AuthPagesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthSettingsRouteRouteChildren {
  AuthSettingsAppearanceRoute: typeof AuthSettingsAppearanceRoute
  AuthSettingsGroupsRoute: typeof AuthSettingsGroupsRoute
  AuthSettingsMembersRoute: typeof AuthSettingsMembersRoute
  AuthSettingsOrganizationRoute: typeof AuthSettingsOrganizationRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsTeamsRoute: typeof AuthSettingsTeamsRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsAppearanceRoute: AuthSettingsAppearanceRoute,
  AuthSettingsGroupsRoute: AuthSettingsGroupsRoute,
  AuthSettingsMembersRoute: AuthSettingsMembersRoute,
  AuthSettingsOrganizationRoute: AuthSettingsOrganizationRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsTeamsRoute: AuthSettingsTeamsRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthSearchRoute: typeof AuthSearchRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthPagesIdRoute: typeof AuthPagesIdRoute
  AuthSpacesSlugRoute: typeof AuthSpacesSlugRoute
  AuthSpacesIndexRoute: typeof AuthSpacesIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthSearchRoute: AuthSearchRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthPagesIdRoute: AuthPagesIdRoute,
  AuthSpacesSlugRoute: AuthSpacesSlugRoute,
  AuthSpacesIndexRoute: AuthSpacesIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
